import {
  faBook,
  faList,
  faPlus,
  faUsers,
} from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import Head from "next/head";
import Link from "next/link";
import { useContext } from "react";
import LayoutMain from "~/components/LayoutMain";
import { AuthContext } from "~/context/AuthContext";
const Page = () => {
  const auth = useContext(AuthContext);
  return (
    <>
      <Head>
        <title>Apa Reports</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="row justify-content-center">
        {auth.role == "Admin" && (
          <>
            <div className="col-auto mb-2">
              <Link href={"/categories"}>
                <div
                  className="card"
                  style={{ color: "white", backgroundColor: "#5036a0" }}
                >
                  <div className="card-body p-5">
                    <FontAwesomeIcon
                      icon={faList}
                      className="ml-3"
                      style={{ height: "25px" }}
                    />
                    <span style={{ fontSize: "25px" }}>دسته بندی گزارشات</span>
                  </div>
                </div>
              </Link>
            </div>

            <div className="col-auto mb-2">
              <Link href={"/users"}>
                <div
                  className="card"
                  style={{ color: "white", backgroundColor: "#5036a0" }}
                >
                  <div className="card-body p-5">
                    <FontAwesomeIcon
                      icon={faUsers}
                      className="ml-3"
                      style={{ height: "25px" }}
                    />
                    <span style={{ fontSize: "25px" }}>کاربران</span>
                  </div>
                </div>
              </Link>
            </div>
          </>
        )}

        <div className="col-auto mb-2">
          <Link href={"/reports"}>
            <div
              className="card"
              style={{ color: "white", backgroundColor: "#5036a0" }}
            >
              <div className="card-body p-5">
                <FontAwesomeIcon
                  icon={faBook}
                  className="ml-3"
                  style={{ height: "25px" }}
                />
                <span style={{ fontSize: "25px" }}>گزارشات</span>
              </div>
            </div>
          </Link>
        </div>

        {auth.role == "Apa" && (
          <div className="col-auto mb-2">
            <Link href={"/reports/submit"}>
              <div
                className="card"
                style={{ color: "white", backgroundColor: "#5036a0" }}
              >
                <div className="card-body p-5">
                  <FontAwesomeIcon
                    icon={faPlus}
                    className="ml-3"
                    style={{ height: "25px" }}
                  />
                  <span style={{ fontSize: "25px" }}>ثبت گزارش</span>
                </div>
              </div>
            </Link>
          </div>
        )}
      </div>
    </>
  );
};

Page.Layout = LayoutMain;
export default Page;
